version: "3"
services:
  db:
    image: mysql/mysql-server:latest
    ports:
      - "3305:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}"

  testDB:
    image: mysql/mysql-server:latest
    ports:
      - "3308:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=dbpass"
      - "MYSQL_DATABASE=test_db"
